### ISSUE TITLE
Update Question

### ISSUE THREAD

**Issue by 3raxton** [aCluelessDanny/UeberPlayer#12]
Great work on this again. I love how seamlessly the update checker has integrated into my workflow. Regarding that, I'm curious if you know how an update would affect the current state of the widget. I've edited a few things for my version of the widget (larger album artwork, progress bar, etc.), and I'm worried that the update would override my preferences in the index.jsx file. 

Do you have any idea if the updates would override those settings? Thanks again for all your hard work on the widget!

**Comment by aCluelessDanny** [comment]
Yeah, chances are it'll override things because the update mechanism is rather simple. It only grabs the latest build, so you can replace everything on top of it. Even the configurable settings revert to their defaults, though I'm probably gonna make that update mechanism a bit more fleshed out for this use case.

What you could do is clone the repo and edit it to your liking. And whenever it shows there's an update (since it'll check my repo for version changes), you can pull and merge my changes with your repo (there might be conflicts which you'll have to judge how to handle, depending on what you edited). Then just copy that build into your widgets folder, by running `gulp` in the command line and copying what's inside the `dist` folder (I should probably make this step an automatic thing now that I think about it, ahah)

**Comment by 3raxton** [comment]
That makes sense, thanks for helping me understand the update mechanism a bit more. Would be nice to see the update mechanism fleshed, but that's ultimately your choice, so don't feel rushed. 

Great idea on cloning the repo then pulling and merging your changes on top of it, excluding the conflicts. I'll think about what the right move is for me on this, but I can hold off for a bit until I feel like there's an update I need. Thanks!
