### ISSUE TITLE
Artwork cache question

### ISSUE THREAD

**Issue by 3raxton** [aCluelessDanny/UeberPlayer#13]
Hey! Your code has been working seamlessly for me, and I'm happy that you're carrying on this project. I have a quick question for you about the album artwork size that is cached. 

I'm working on a project and am using the cache to supply me with the artwork needed. I see it's sized at 640x640, and I'm curious if I can change the track script to make the size 1000x1000. 

Can you give me any insight on what I can do to resize the images that are cached? If so, I'd appreciate it. Thanks again for all your hard work!

**Comment by aCluelessDanny** [comment]
Hey there! So to my knowledge, I _think_ this depends on the track, as the script basically downloads the artwork from the image URL given (Spotify) or reconstructs the image straight from the track artwork's data (Apple Music), so the image size isn't something you can control at that stage. I'm not sure if music artists follow some kind of standard when it comes to artwork, but I wouldn't be surprised since a lot of them are coincidentally 640x640.

What you can do though is use a third-party command line tool like `convert` to rescale the image _after_ they've been added to the cache (so basically add another shell command around the end of `extractSpotifyArt()` or `extractMusicArt()`). And also if you wanna to apply this to the cached artwork you currently have, you can just delete them from the "cache" folder in the widget and redownload the images (or run a command to affect all the images in that folder in bulk)~

**Comment by 3raxton** [comment]
I gotcha. It wouldn't surprise me if there was something like that as some of the artworks from the folder were different sizes but all roughly around 640x640. I remember years back when most artworks were 500x500. 

Good to know about the command line; I was working in Figma and resized using the tools it has, which wasn't bad. I just wasn't sure if there was a way I could change the size of the cached images. I appreciate the details you shared with the shell command and cache details; it helps me understand it much better!
