### ISSUE TITLE
No Artwork

### ISSUE THREAD

**Issue by CenterStage40** [aCluelessDanny/UeberPlayer#7]
Not sure what's going on but my player doesn't generate any artwork, just says it can't find the .jpg for any music. Any ideas? Using Apple Music btw

**Comment by aCluelessDanny** [comment]
In _theory_, it should work alright, but I'm afraid I can't test this with full confidence; since I don't have an Apple Music subscription (I can only really test with locally stored tracks).

I just put out a new release with a few changes and reworks, so maybe that'll do the trick. Do tell if it does or not

**Comment by IbrahimFadel** [comment]
I also had this problem on Mojave with Apple Music. For me the solution was to edit ```lib/getTrack.scpt``` in the subroutine ```extractMusicArt```

Instead of:
```
set myAltPath to (myAltPath's text items 1 thru -2 as string) & "/"
```
I did:
```
set myAltPath to (myAltPath's text items 1 thru -3 as string) & "/"
```

This made the path correct for me. If you're unsure, the way i debugged was just doing
```
display dialog myAltPath
```
to see where it was going

**Comment by aCluelessDanny** [comment]
Duly noted for the next update when I get around to it. Kinda odd that change is necessary, though I can't test that on my end

**Comment by noatpad** [comment]
Closing this now as the new release also applies the fix mentioned just above and _hopefully_ everything should be working now~
